use crate::error::CoreError;
use crate::model::SubscriptionUserInfo;
use serde_yaml::{Mapping, Value};

/// Generates a clean base Mihomo configuration template
pub fn generate_base_config(
    mixed_port: u16,
    controller_port: u16,
    secret: &str,
    tun_enabled: bool,
) -> String {
    format!(
        r#"# Mihomo configuration generated by Gihomo
mixed-port: {mixed_port}
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:{controller_port}
secret: "{secret}"

tun:
  enable: {tun_enabled}
  device: gihomo
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
  iproute2-table-index: 2024
  iproute2-rule-index: 9020

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
"#
    )
}

/// Enforces local-only controller access and the application's secret on a loaded config.
pub fn secure_controller_config(
    config_yaml: &str,
    controller_port: u16,
    secret: &str,
) -> Result<String, CoreError> {
    let mut config: Value = serde_yaml::from_str(config_yaml)
        .map_err(|e| CoreError::ConfigMerge(format!("Invalid Mihomo config: {}", e)))?;
    let mapping = config.as_mapping_mut().ok_or_else(|| {
        CoreError::ConfigMerge("Mihomo config must be a YAML mapping".to_string())
    })?;

    mapping.insert(
        Value::String("external-controller".to_string()),
        Value::String(format!("127.0.0.1:{}", controller_port)),
    );
    mapping.insert(
        Value::String("secret".to_string()),
        Value::String(secret.to_string()),
    );

    serde_yaml::to_string(&config)
        .map_err(|e| CoreError::ConfigMerge(format!("Failed to serialize Mihomo config: {}", e)))
}

/// Merges user base settings with subscription content (proxies, proxy-groups, rules, etc.)
pub fn merge_subscription_config(
    base_template_yaml: &str,
    subscription_raw_yaml: &str,
    tun_enabled: bool,
    mixed_port: u16,
    controller_port: u16,
    secret: &str,
) -> Result<String, CoreError> {
    let mut base_value: Value = serde_yaml::from_str(base_template_yaml)
        .map_err(|e| CoreError::ConfigMerge(format!("Invalid base template YAML: {}", e)))?;

    let sub_value: Value = serde_yaml::from_str(subscription_raw_yaml).map_err(|e| {
        CoreError::InvalidSubscription(format!("Subscription is not valid YAML: {}", e))
    })?;

    let base_map = base_value
        .as_mapping_mut()
        .ok_or_else(|| CoreError::ConfigMerge("Base config must be a YAML mapping".to_string()))?;

    // Override fundamental ports & controller
    base_map.insert(
        Value::String("mixed-port".to_string()),
        Value::Number(mixed_port.into()),
    );
    base_map.insert(
        Value::String("external-controller".to_string()),
        Value::String(format!("127.0.0.1:{}", controller_port)),
    );
    base_map.insert(
        Value::String("secret".to_string()),
        Value::String(secret.to_string()),
    );

    // Override TUN status in base mapping
    if let Some(tun_val) = base_map.get_mut("tun") {
        if let Some(tun_map) = tun_val.as_mapping_mut() {
            tun_map.insert(
                Value::String("enable".to_string()),
                Value::Bool(tun_enabled),
            );
        }
    } else {
        let mut tun_map = Mapping::new();
        tun_map.insert(
            Value::String("enable".to_string()),
            Value::Bool(tun_enabled),
        );
        tun_map.insert(
            Value::String("device".to_string()),
            Value::String("gihomo".to_string()),
        );
        tun_map.insert(
            Value::String("stack".to_string()),
            Value::String("mixed".to_string()),
        );
        tun_map.insert(Value::String("auto-route".to_string()), Value::Bool(true));
        tun_map.insert(
            Value::String("auto-detect-interface".to_string()),
            Value::Bool(true),
        );
        base_map.insert(Value::String("tun".to_string()), Value::Mapping(tun_map));
    }

    // Merge components from subscription YAML
    if let Some(sub_map) = sub_value.as_mapping() {
        let keys_to_copy = [
            "proxies",
            "proxy-groups",
            "proxy-providers",
            "rule-providers",
            "rules",
            "sub-rules",
            "sniffer",
            "hosts",
            "geox-url",
            "geo-auto-update",
            "profile",
            "script",
        ];

        for key in keys_to_copy {
            let k = Value::String(key.to_string());
            if let Some(v) = sub_map.get(&k) {
                base_map.insert(k, v.clone());
            }
        }

        // Deep merge custom DNS if provided by subscription
        if let Some(sub_dns) = sub_map.get("dns") {
            if let Some(sub_dns_map) = sub_dns.as_mapping() {
                if let Some(base_dns) = base_map.get_mut("dns") {
                    if let Some(base_dns_map) = base_dns.as_mapping_mut() {
                        for (k, v) in sub_dns_map {
                            base_dns_map.insert(k.clone(), v.clone());
                        }
                        base_dns_map.insert(Value::String("enable".to_string()), Value::Bool(true));
                    }
                } else {
                    base_map.insert(Value::String("dns".to_string()), sub_dns.clone());
                }
            }
        }
    }

    serde_yaml::to_string(&base_value)
        .map_err(|e| CoreError::ConfigMerge(format!("Failed to serialize merged YAML: {}", e)))
}

/// Parses "Subscription-Userinfo: upload=1234; download=5678; total=9999; expire=1700000000"
pub fn parse_user_info_header(header_val: &str) -> Option<SubscriptionUserInfo> {
    let mut upload = 0u64;
    let mut download = 0u64;
    let mut total = 0u64;
    let mut expire = None;

    for part in header_val.split(';') {
        let trimmed = part.trim();
        let mut kv = trimmed.split('=');
        if let (Some(k), Some(v)) = (kv.next(), kv.next()) {
            match k.trim() {
                "upload" => upload = v.trim().parse().unwrap_or(0),
                "download" => download = v.trim().parse().unwrap_or(0),
                "total" => total = v.trim().parse().unwrap_or(0),
                "expire" => expire = v.trim().parse().ok(),
                _ => {}
            }
        }
    }

    if total > 0 || upload > 0 || download > 0 {
        Some(SubscriptionUserInfo {
            upload,
            download,
            total,
            expire,
        })
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_user_info() {
        let header =
            "upload=1073741824; download=2147483648; total=107374182400; expire=1750000000";
        let info = parse_user_info_header(header).expect("Must parse header");
        assert_eq!(info.upload, 1073741824);
        assert_eq!(info.download, 2147483648);
        assert_eq!(info.total, 107374182400);
        assert_eq!(info.expire, Some(1750000000));
        assert_eq!(SubscriptionUserInfo::format_bytes(info.total), "100.00 GB");
    }

    #[test]
    fn test_merge_subscription_config() {
        let base = generate_base_config(7890, 9090, "secret123", false);
        let sub = r#"
proxies:
  - name: "HK-01"
    type: ss
    server: server.example.com
    port: 443
    cipher: aes-128-gcm
    password: pass
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - HK-01
rules:
  - MATCH,PROXY
"#;

        let merged = merge_subscription_config(&base, sub, true, 7890, 9090, "secret123")
            .expect("Merge must succeed");

        assert!(merged.contains("mixed-port: 7890"));
        assert!(merged.contains("external-controller: 127.0.0.1:9090"));
        assert!(merged.contains("HK-01"));
        assert!(merged.contains("MATCH,PROXY"));
        assert!(merged.contains("enable: true")); // TUN enabled
    }

    #[test]
    fn test_generated_controller_is_local_only() {
        let config = generate_base_config(7890, 9090, "secret", false);
        assert!(config.contains("external-controller: 127.0.0.1:9090"));
    }

    #[test]
    fn test_secure_controller_config_overrides_subscription_values() {
        let config = "external-controller: 0.0.0.0:9090\nsecret: ''\n";
        let secured = secure_controller_config(config, 9091, "persisted-secret")
            .expect("valid config should be secured");
        let parsed: Value = serde_yaml::from_str(&secured).expect("secured YAML should parse");
        assert_eq!(parsed["external-controller"], "127.0.0.1:9091");
        assert_eq!(parsed["secret"], "persisted-secret");
    }

    #[test]
    fn test_merge_subscription_preserves_advanced_directives() {
        let base = generate_base_config(7890, 9090, "secret123", false);
        let sub = r#"
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
hosts:
  'example.com': 1.1.1.1
geox-url:
  geoip: "https://hub.fastgit.xyz/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb"
dns:
  nameserver-policy:
    'geosite:cn': [223.5.5.5, 119.29.29.29]
proxies:
  - name: "TEST-01"
    type: ss
    server: 127.0.0.1
    port: 1080
    cipher: aes-128-gcm
    password: test
rules:
  - MATCH,DIRECT
"#;

        let merged = merge_subscription_config(&base, sub, false, 7890, 9090, "secret123")
            .expect("Merge must succeed");

        assert!(merged.contains("sniffer:"));
        assert!(merged.contains("hosts:"));
        assert!(merged.contains("geox-url:"));
        assert!(merged.contains("nameserver-policy:"));
        assert!(merged.contains("TEST-01"));
    }
}
